name: Consulta mejoras

on:
  repository_dispatch:
    types: [consulta_mejora]

jobs:
  consultar:
    runs-on: ubuntu-latest
    steps:
      - name: Mejora consultada
        run: |
          echo "Consulta realizada."
          echo "Mejora consultada: ${{ github.event.client_payload.mejora }}"