name: Crear Cliente

on:
  push:
    paths:
      - "clientes/**"

jobs:
  crear:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener c贸digo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Detectar creaci贸n de archivos
        run: |
          if git rev-parse HEAD~1 >/dev/null 2>&1; then
            DIFF=$(git diff --name-status HEAD~1 HEAD)
          else
            DIFF=$(git diff --name-status HEAD)
          fi

          if echo "$DIFF" | grep "^A"; then
              echo "Archivos creados:"
              echo "$DIFF" | grep "^A"
              echo "Cliente(s) creado. Notificaci贸n del equipo de AXA."
          else
              echo "No hubo creaci贸n de cliente. Finalizando sin error."
          fi
